[package]
name = "struct_check"
version = "0.1.0"
edition = "2021"

[dependencies]
gimli = "0.27.0"
memmap2 = "0.5.8"
object = "0.30.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
